---
- name: Apply Windows Server 2022 STIG using Ansible Lockdown role
  hosts: "{{ run_against }}"

  tasks:
    - name: Run the Ansible Lockdown role
      ansible.builtin.import_role:
        name: windows-2022-stig
